# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiTemplate < Formula
  desc "ci-template"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.19"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/ci-template/releases/download/v1.0.19/ci-template_v1.0.19_darwin_amd64.tar.gz"
      sha256 "53b02032cca9ab031563148ac09357ffdcafc853dafbede016c2ff14d384e7ae"

      def install
        bin.install "ci-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/ci-template/releases/download/v1.0.19/ci-template_v1.0.19_darwin_arm64.tar.gz"
      sha256 "012fb2b01f678abad3da7e6c4a54cc135df2557088c555b2e18bb0297079186d"

      def install
        bin.install "ci-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/ci-template/releases/download/v1.0.19/ci-template_v1.0.19_linux_amd64.tar.gz"
      sha256 "bfa50cb050fd61c523b8de9817c937965315cc2a5a6fdbfdcbd6253b74fe321e"
      def install
        bin.install "ci-template"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/ci-template/releases/download/v1.0.19/ci-template_v1.0.19_linux_arm64.tar.gz"
      sha256 "e7af54ffaf7fdbcc9850855e0f8ad6c0e5f3f711575b4737298a5cf32fa561eb"
      def install
        bin.install "ci-template"
      end
    end
  end

  test do
    system "#{bin}/ci-template"
  end
end
