# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godedup < Formula
  desc "Find structurally duplicate functions in Go code"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.1/godedup_v1.0.1_darwin_amd64.tar.gz"
      sha256 "e51d7034d855a4245292dcf5e6b4512833bd271f8dabfbb4995abc1d515e181c"

      define_method(:install) do
        bin.install "godedup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.1/godedup_v1.0.1_darwin_arm64.tar.gz"
      sha256 "4cb74afe8109fdc6f8205c2093ffa600de4bb1ef92c6b5c41e5972a93e63bef2"

      define_method(:install) do
        bin.install "godedup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.1/godedup_v1.0.1_linux_amd64.tar.gz"
      sha256 "df6dfc74c59806f2811e2c1e1b318c1c9bec8e51f5a805c9a5cb2e580295fe91"
      define_method(:install) do
        bin.install "godedup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.1/godedup_v1.0.1_linux_arm64.tar.gz"
      sha256 "eabf6e6a287936d4c690da3d2b3e49cad964743d54ed5f5ab38afd7c98f2490d"
      define_method(:install) do
        bin.install "godedup"
      end
    end
  end

  test do
    system "#{bin}/godedup"
  end
end
