# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godedup < Formula
  desc "Find structurally duplicate functions in Go code"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.4/godedup_v1.0.4_darwin_amd64.tar.gz"
      sha256 "44954f952e377cc4f5b1a0bd13c1bb3886b81786bcb7b9d56d5797f1974458f4"

      define_method(:install) do
        bin.install "godedup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.4/godedup_v1.0.4_darwin_arm64.tar.gz"
      sha256 "5e29a80f5ebce044d03bfa0f167a45b3e1892610c1a382ee93341e90e64626f9"

      define_method(:install) do
        bin.install "godedup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.4/godedup_v1.0.4_linux_amd64.tar.gz"
      sha256 "e45fd7171b9b378338dad815a676ad34550326b64fc9737b7cd5cd259137f38d"
      define_method(:install) do
        bin.install "godedup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/godedup/releases/download/v1.0.4/godedup_v1.0.4_linux_arm64.tar.gz"
      sha256 "3699637b09c6a02afef49c6e7484b9f7f6bdcb5c2ed564f9622d9ac07474a522"
      define_method(:install) do
        bin.install "godedup"
      end
    end
  end

  test do
    system "#{bin}/godedup"
  end
end
