# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofromdb < Formula
  desc "Find structurally duplicate functions in Go code"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.10/gofromdb_v1.0.10_darwin_amd64.tar.gz"
      sha256 "189b7537703ac65dfb4c4f9351644f5c2b582499c418c3e4644e3868bb908228"

      define_method(:install) do
        bin.install "gofromdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.10/gofromdb_v1.0.10_darwin_arm64.tar.gz"
      sha256 "7cc7053b78c09685f18348226ba2f173b8bae79ab6b0d0606e6223a92191dc99"

      define_method(:install) do
        bin.install "gofromdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.10/gofromdb_v1.0.10_linux_amd64.tar.gz"
      sha256 "d6c2543cb6e40fbdadf9c207175b6975fac09f8ac9d45387d413698153178aa2"
      define_method(:install) do
        bin.install "gofromdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.10/gofromdb_v1.0.10_linux_arm64.tar.gz"
      sha256 "7900fbb8be64acf4283e4738d83e206fd870cbef538dad013c9f6c7a5c8e5c22"
      define_method(:install) do
        bin.install "gofromdb"
      end
    end
  end

  test do
    system "#{bin}/gofromdb"
  end
end
