# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofromdb < Formula
  desc "Find structurally duplicate functions in Go code"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.12/gofromdb_v1.0.12_darwin_amd64.tar.gz"
      sha256 "87ad5303ab5b368a8e757401325a8c9f3220b8dea8e32301077dfd5b5fa9bd72"

      define_method(:install) do
        bin.install "gofromdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.12/gofromdb_v1.0.12_darwin_arm64.tar.gz"
      sha256 "7cb1f9faf71e9089344dce3934963021c0c10c433f77af5051060d3039a091a0"

      define_method(:install) do
        bin.install "gofromdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.12/gofromdb_v1.0.12_linux_amd64.tar.gz"
      sha256 "f7dcf479ca200c34fb45c44e5b3456aadd438d79bfe2c59d822f3a9ecef46e75"
      define_method(:install) do
        bin.install "gofromdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/gofromdb/releases/download/v1.0.12/gofromdb_v1.0.12_linux_arm64.tar.gz"
      sha256 "76eb62f97b453ae5c74cd4337301c04e630ffc5445762a6bde04150fd8ec8dd8"
      define_method(:install) do
        bin.install "gofromdb"
      end
    end
  end

  test do
    system "#{bin}/gofromdb"
  end
end
