# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Katomik < Formula
  desc "Atomic apply of multiple Kubernetes manifests with rollback on failure."
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.2/katomik_v1.0.2_darwin_amd64.tar.gz"
      sha256 "8d9de15a310c124c11141421c49514d794dfaf894e5fba885669ef0a4a1c6e53"

      def install
        bin.install "katomik"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.2/katomik_v1.0.2_darwin_arm64.tar.gz"
      sha256 "b242b183e2ab6dd156d4cf472395a4714bc6738484a03463331f8eb7cd26ef73"

      def install
        bin.install "katomik"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.2/katomik_v1.0.2_linux_amd64.tar.gz"
      sha256 "ea6ca9e3d51a8fc8ee80cf70440f6dee5d83c5858c6f0c25ffc4d9b67351a559"
      def install
        bin.install "katomik"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.2/katomik_v1.0.2_linux_arm64.tar.gz"
      sha256 "7b2318711399f6a5e66495c94f798712d0be60c64e7676a96e956e8048857bd5"
      def install
        bin.install "katomik"
      end
    end
  end

  test do
    system "#{bin}/katomik"
  end
end
