# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Katomik < Formula
  desc "Atomic apply of multiple Kubernetes manifests with rollback on failure."
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.4/katomik_v1.0.4_darwin_amd64.tar.gz"
      sha256 "a237add6b5002e7f007ab8de3e49ea641a9131fdedb1ed58dd0cd1d3651d974d"

      def install
        bin.install "katomik"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.4/katomik_v1.0.4_darwin_arm64.tar.gz"
      sha256 "c77e66774a20e0de1d4b565f5ed2e5ea8219f7b4825217829bb8b6fbe7c4b2f7"

      def install
        bin.install "katomik"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.4/katomik_v1.0.4_linux_amd64.tar.gz"
      sha256 "f692de2ce912efabef0169dbe3b9c0f5463426225af110f5ee44861b20abf4a3"
      def install
        bin.install "katomik"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.4/katomik_v1.0.4_linux_arm64.tar.gz"
      sha256 "7b3455ea64d9b7f9e60e00e2c32fe44fc625012492245eb054f9c0aee1b7cb71"
      def install
        bin.install "katomik"
      end
    end
  end

  test do
    system "#{bin}/katomik"
  end
end
