# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Katomik < Formula
  desc "Atomic apply of multiple Kubernetes manifests with rollback on failure."
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.3/katomik_v1.0.3_darwin_amd64.tar.gz"
      sha256 "87188b32fed13bc586069f78cbf07fb934bf3cab200f4db2492e60868b5efd49"

      def install
        bin.install "katomik"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.3/katomik_v1.0.3_darwin_arm64.tar.gz"
      sha256 "662f82b5afadbc52b6dea19e3a962b940063940aebe75b12aec0ab15062a8141"

      def install
        bin.install "katomik"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.3/katomik_v1.0.3_linux_amd64.tar.gz"
      sha256 "ac3690ac1e66416fb40f16ed56e0ce3db6de9524e40b32ea7915c511ba7f197e"
      def install
        bin.install "katomik"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/katomik/releases/download/v1.0.3/katomik_v1.0.3_linux_arm64.tar.gz"
      sha256 "09cdc60e7a3bd23196ce91443e6e1319ad4269f649e214642f699d99937868e7"
      def install
        bin.install "katomik"
      end
    end
  end

  test do
    system "#{bin}/katomik"
  end
end
