# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlSyncpod < Formula
  desc "High-Speed File Transfer to and from PVCs"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.5/kubectl-syncpod_v1.0.5_darwin_amd64.tar.gz"
      sha256 "edfbaa42a9baa23de434b295e223ec4b716a80e39de21ca7579a87d37871df44"

      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.5/kubectl-syncpod_v1.0.5_darwin_arm64.tar.gz"
      sha256 "41d61f711412088ac07ae17480c7d3b0adaae32c07eb13f6e42bbb85ca61869c"

      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.5/kubectl-syncpod_v1.0.5_linux_amd64.tar.gz"
      sha256 "6dc57d2d8d66f3747f45ed4f79258d045de643b2b73cf739e403b3ef85439038"
      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.5/kubectl-syncpod_v1.0.5_linux_arm64.tar.gz"
      sha256 "14908b2ce0850d1bc3146b2ab9760c56b3412067658c68f6164dcbb1c0ce9501"
      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
  end

  test do
    system "#{bin}/kubectl-syncpod"
  end
end
