# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlSyncpod < Formula
  desc "High-Speed File Transfer to and from PVCs"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.6/kubectl-syncpod_v1.0.6_darwin_amd64.tar.gz"
      sha256 "db7e8891d71cfcd7f46d17d996c130bbd6e62adf497513b1570cd0b84659691c"

      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.6/kubectl-syncpod_v1.0.6_darwin_arm64.tar.gz"
      sha256 "35c7df54ca9ddf455c7b15a83a8366fa9a34a650fa22d75d6f606ed795db3156"

      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.6/kubectl-syncpod_v1.0.6_linux_amd64.tar.gz"
      sha256 "408991f603031488e878ce2782cd0794a90e795bcdf0afed2e61cd4ec96a1b3e"
      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/kubectl-syncpod/releases/download/v1.0.6/kubectl-syncpod_v1.0.6_linux_arm64.tar.gz"
      sha256 "3b622a3140b7451d229f6584b198490b3a867abf6ba02510a94841fe4500c526"
      define_method(:install) do
        bin.install "kubectl-syncpod"
      end
    end
  end

  test do
    system "#{bin}/kubectl-syncpod"
  end
end
