# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlAtomicApply < Formula
  desc "Kubectl plugin for atomic apply of multiple Kubernetes manifests with rollback on failure."
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/kubectl-atomic_apply/releases/download/v1.0.1/kubectl-atomic_apply_v1.0.1_darwin_amd64.tar.gz"
      sha256 "906d7614167d93517ebb20e7b686cbe9a7f23d970e6495a7742049a856b8a96e"

      def install
        bin.install "kubectl-atomic_apply"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/kubectl-atomic_apply/releases/download/v1.0.1/kubectl-atomic_apply_v1.0.1_darwin_arm64.tar.gz"
      sha256 "96552e6cb916939709785be04be067be3cb7d8874c3c13b24e86a6badcfdc60f"

      def install
        bin.install "kubectl-atomic_apply"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/kubectl-atomic_apply/releases/download/v1.0.1/kubectl-atomic_apply_v1.0.1_linux_amd64.tar.gz"
      sha256 "a73bc86590feab7ca7e9212fc298e0da0339ff2af5d0a9b3b465600a945c07e1"
      def install
        bin.install "kubectl-atomic_apply"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/kubectl-atomic_apply/releases/download/v1.0.1/kubectl-atomic_apply_v1.0.1_linux_arm64.tar.gz"
      sha256 "6b24eca639c73ea76a7a066b5d56f443e73456436bce2bfc638e34240854e1a2"
      def install
        bin.install "kubectl-atomic_apply"
      end
    end
  end

  test do
    system "#{bin}/kubectl-atomic_apply"
  end
end
