# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PgdumpEach < Formula
  desc "PostgreSQL version upgrade assistant"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/pgdump-each/releases/download/v1.0.14/pgdump-each_v1.0.14_darwin_amd64.tar.gz"
      sha256 "0744a3dd06ab884b13dd84885f6e7a4b53378088e3b3a776d14efa4486058cc3"

      def install
        bin.install "pgdump-each"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/pgdump-each/releases/download/v1.0.14/pgdump-each_v1.0.14_darwin_arm64.tar.gz"
      sha256 "0b8b0c4e4ac961cb3abeed29eebee77d6529d8cdb15df1f5e8fadea3f8550417"

      def install
        bin.install "pgdump-each"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashmap-kz/pgdump-each/releases/download/v1.0.14/pgdump-each_v1.0.14_linux_amd64.tar.gz"
        sha256 "0781b2b120bdb68ded7613a0643505eb81b20242fac09f5c7a080563a834c466"

        def install
          bin.install "pgdump-each"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashmap-kz/pgdump-each/releases/download/v1.0.14/pgdump-each_v1.0.14_linux_arm64.tar.gz"
        sha256 "f2ec7d63791b0ca66c3631fc9006b0673f1c93a8c889c28e13e3fb343d025840"

        def install
          bin.install "pgdump-each"
        end
      end
    end
  end

  test do
    system "#{bin}/pgdump-each"
  end
end
