# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsize < Formula
  desc "ncdu for postgres"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.6/pgsize_v0.0.6_darwin_amd64.tar.gz"
      sha256 "27029d5cbea7ada94fa6ae86059aa16f82c9b0feb6f74a5ced7546052187c7b0"

      define_method(:install) do
        bin.install "pgsize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.6/pgsize_v0.0.6_darwin_arm64.tar.gz"
      sha256 "dc8127063848043274fa3be3ee46a1baf1919e65abed232410277b89dc7d48b9"

      define_method(:install) do
        bin.install "pgsize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.6/pgsize_v0.0.6_linux_amd64.tar.gz"
      sha256 "0cbedcbfad113a00d43c0bf02482ccd7286bcd128f7acdff48257409bc0cc3a3"
      define_method(:install) do
        bin.install "pgsize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.6/pgsize_v0.0.6_linux_arm64.tar.gz"
      sha256 "57e7851b4b618f625b11d7a7a623e5819db4f03060d81eb1534ddaffa2ce4e67"
      define_method(:install) do
        bin.install "pgsize"
      end
    end
  end

  test do
    system "#{bin}/pgsize"
  end
end
