# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsize < Formula
  desc "ncdu for postgres"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.1/pgsize_v0.0.1_darwin_amd64.tar.gz"
      sha256 "be6c99a9c30b83b8faa3783d2d252b431846bcb46399bad80416e40064726c11"

      define_method(:install) do
        bin.install "pgsize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.1/pgsize_v0.0.1_darwin_arm64.tar.gz"
      sha256 "fd9c4f6249df2cdaff19a088415f73e8bea1e2dafc006607f576120d98c9f77d"

      define_method(:install) do
        bin.install "pgsize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.1/pgsize_v0.0.1_linux_amd64.tar.gz"
      sha256 "42fd1f484a84988c65861e7fe72715f87ced9bb1ca1e4a230889319c69e73d37"
      define_method(:install) do
        bin.install "pgsize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/pgsize/releases/download/v0.0.1/pgsize_v0.0.1_linux_arm64.tar.gz"
      sha256 "ae7ae139c97f633fb1da6051020d45314e01c7fa25332856c3a2c48eea95cd98"
      define_method(:install) do
        bin.install "pgsize"
      end
    end
  end

  test do
    system "#{bin}/pgsize"
  end
end
