# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rconf < Formula
  desc "Execute multiple shell scripts on multiple remote hosts via SSH"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.6/rconf_v1.0.6_darwin_amd64.tar.gz"
      sha256 "d2511464069fe9322f841af819c6675edea61f18dc7c847ec2f9ca4e81f46c98"

      def install
        bin.install "rconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.6/rconf_v1.0.6_darwin_arm64.tar.gz"
      sha256 "355ad1b90a88bedafac5cd7ec30034f3d50089f6bd5b6314a6e5457b789ee961"

      def install
        bin.install "rconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.6/rconf_v1.0.6_linux_amd64.tar.gz"
        sha256 "d4854b975b1905b8c95316ac3bdcdebc1ab8190c33eacda37f0872a7c54453e2"

        def install
          bin.install "rconf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.6/rconf_v1.0.6_linux_arm64.tar.gz"
        sha256 "14dd34accbe2d33e291cb1a112344cde66a8e8a5eac5ffb877e9e0e8ff899d58"

        def install
          bin.install "rconf"
        end
      end
    end
  end

  test do
    system "#{bin}/rconf"
  end
end
