# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rconf < Formula
  desc "Execute multiple shell scripts on multiple remote hosts via SSH"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.7/rconf_v1.0.7_darwin_amd64.tar.gz"
      sha256 "981dd9717dd4cbd8b91e15f0657a1d704c4be5cb028481e6956d2741fe65ca3e"

      def install
        bin.install "rconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.7/rconf_v1.0.7_darwin_arm64.tar.gz"
      sha256 "78b98ac1ebe3fae977342c1bdcefc95c850b728ea3623dc242857f9c8ac2ed93"

      def install
        bin.install "rconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.7/rconf_v1.0.7_linux_amd64.tar.gz"
        sha256 "59d1490047b0547512d5d1329909caf18b9596f6797023f29e69adb7d342803c"

        def install
          bin.install "rconf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashmap-kz/rconf/releases/download/v1.0.7/rconf_v1.0.7_linux_arm64.tar.gz"
        sha256 "9a8b50f485114189a36531216cf3e07af1ae81c16bf17adadfdc0bcda36d1547"

        def install
          bin.install "rconf"
        end
      end
    end
  end

  test do
    system "#{bin}/rconf"
  end
end
