# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smallci < Formula
  desc "A minimal local CI runner"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.2/smallci_v1.0.2_darwin_amd64.tar.gz"
      sha256 "1bee2a346c2507e79807e79d06db175c5db19d54c4139fb2232d73731b17c4fe"

      define_method(:install) do
        bin.install "smallci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.2/smallci_v1.0.2_darwin_arm64.tar.gz"
      sha256 "a64fc756eb6d35c68c33a8e5c4db0f677dadcd86884d49cb4648cd34bdbd77a7"

      define_method(:install) do
        bin.install "smallci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.2/smallci_v1.0.2_linux_amd64.tar.gz"
      sha256 "ab6c618b37e122feeb78449e05026ad4c03bdc5d41570438c50a4e5ac9d18d5e"
      define_method(:install) do
        bin.install "smallci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.2/smallci_v1.0.2_linux_arm64.tar.gz"
      sha256 "895f98da7928280b7582e7f2d8516199acd768ffaa0db2ff719edc71c076999a"
      define_method(:install) do
        bin.install "smallci"
      end
    end
  end

  test do
    system "#{bin}/smallci"
  end
end
