# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smallci < Formula
  desc "A minimal local CI runner"
  homepage "https://github.com/hashmap-kz/homebrew-tap"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.6/smallci_v1.0.6_darwin_amd64.tar.gz"
      sha256 "581eebc50c3edf1ce186758c1c795c6c21e243597f2a298edb0fc7d3136651ae"

      define_method(:install) do
        bin.install "smallci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.6/smallci_v1.0.6_darwin_arm64.tar.gz"
      sha256 "e0693119fcb47e2873b0cbee69eddca3e4280f833d613272a5e66879da6347b3"

      define_method(:install) do
        bin.install "smallci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.6/smallci_v1.0.6_linux_amd64.tar.gz"
      sha256 "d7b616aafa39f13616a3001c3f31ad38be4868eaf6faf3ca009c568c670f4468"
      define_method(:install) do
        bin.install "smallci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashmap-kz/smallci/releases/download/v1.0.6/smallci_v1.0.6_linux_arm64.tar.gz"
      sha256 "89b0c99a1c1ead88f018214c7ab72d61c065b3d5ca0e5ccae027d3197e4e7573"
      define_method(:install) do
        bin.install "smallci"
      end
    end
  end

  test do
    system "#{bin}/smallci"
  end
end
